use base64::Engine;
use once_cell::sync::Lazy;

const SAMPLE_MP4_BASE64: &str = concat!(
    "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAMmbW9vdgAAAGxtdmhkAAAAAAAAAAAA",
    "AAAAAAAD6AAAAGQAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA",
    "AABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAlF0cmFrAAAAXHRraGQAAAADAAAA",
    "AAAAAAAAAAACAAAAAAAAAGQAAAAAAAAAAAAAAAEBAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAA",
    "AAAAAAAAAABAAAAAAAAAAAAAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAABkAAAEAAABAAAA",
    "AAHJbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAC7gAAAFsBVxAAAAAAALWhkbHIAAAAAAAAAAHNv",
    "dW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAABdG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRp",
    "bmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABOHN0YmwAAAB+c3RzZAAAAAAAAAABAAAA",
    "bm1wNGEAAAAAAAAAAQAAAAAAAAAAAAIAEAAAAAC7gAAAAAAANmVzZHMAAAAAA4CAgCUAAgAEgICA",
    "F0AVAAAAAAD6AAAADaYFgICABRGQVuUABoCAgAECAAAAFGJ0cnQAAAAAAAD6AAAADaYAAAAgc3R0",
    "cwAAAAAAAAACAAAABQAABAAAAAABAAACwAAAABxzdHNjAAAAAAAAAAEAAAABAAAABgAAAAEAAAAs",
    "c3RzegAAAAAAAAAAAAAABgAAABcAAAAGAAAABgAAAAYAAAAGAAAABgAAABRzdGNvAAAAAAAAAAEA",
    "AANWAAAAGnNncGQBAAAAcm9sbAAAAAIAAAAB//8AAAAcc2JncAAAAAByb2xsAAAAAQAAAAYAAAAB",
    "AAAAYXVkdGEAAABZbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAs",
    "aWxzdAAAACSpdG9vAAAAHGRhdGEAAAABAAAAAExhdmY2Mi42LjEwMQAAAAhmcmVlAAAAPW1kYXTe",
    "AgBMYXZjNjIuMTkuMTAwAEIgCMEYOCEQBGCMHCEQBGCMHCEQBGCMHCEQBGCMHCEQBGCMHA==",
);

pub(crate) static SAMPLE_MP4_BYTES: Lazy<Vec<u8>> = Lazy::new(|| {
    base64::engine::general_purpose::STANDARD
        .decode(SAMPLE_MP4_BASE64)
        .expect("template validation sample MP4 must be valid base64")
});
