use crate::ffui_core::domain::{
    AudioCodecType, AudioConfig, EncoderType, FFmpegPreset, FilterConfig, PresetStats,
    RateControlMode, VideoConfig,
};

fn empty_stats() -> PresetStats {
    PresetStats {
        usage_count: 0,
        total_input_size_mb: 0.0,
        total_output_size_mb: 0.0,
        total_time_seconds: 0.0,
    }
}

pub(crate) fn smart_presets_for_cpu_only() -> Vec<FFmpegPreset> {
    vec![
        FFmpegPreset {
            id: "smart-hevc-fast".to_string(),
            name: "H.264 Fast".to_string(),
            description:
                "x264 CRF 23 preset medium keeping source resolution for fast, broadly compatible output."
                    .to_string(),
            description_i18n: None,
            global: None,
            input: None,
            mapping: None,
            video: VideoConfig {
                encoder: EncoderType::Libx264,
                rate_control: RateControlMode::Crf,
                quality_value: 23,
                preset: "medium".to_string(),
                tune: None,
                profile: None,
                bitrate_kbps: None,
                max_bitrate_kbps: None,
                buffer_size_kbits: None,
                pass: None,
                level: None,
                gop_size: None,
                bf: None,
                pix_fmt: Some("yuv420p".to_string()),
                b_ref_mode: None,
                rc_lookahead: None,
                spatial_aq: None,
                temporal_aq: None,
            },
            audio: AudioConfig {
                codec: AudioCodecType::Copy,
                bitrate: None,
                sample_rate_hz: None,
                channels: None,
                channel_layout: None,
                loudness_profile: None,
                target_lufs: None,
                loudness_range: None,
                true_peak_db: None,
            },
            filters: FilterConfig {
                scale: None,
                crop: None,
                fps: None,
                vf_chain: None,
                af_chain: None,
                filter_complex: None,
            },
            subtitles: None,
            container: None,
            hardware: None,
            stats: empty_stats(),
            advanced_enabled: Some(false),
            ffmpeg_template: None,
            is_smart_preset: Some(true),
        },
        FFmpegPreset {
            id: "smart-hevc-archive".to_string(),
            name: "H.264 Archival".to_string(),
            description: "x264 CRF 18 preset slow for near visually lossless archival.".to_string(),
            description_i18n: None,
            global: None,
            input: None,
            mapping: None,
            video: VideoConfig {
                encoder: EncoderType::Libx264,
                rate_control: RateControlMode::Crf,
                quality_value: 18,
                preset: "slow".to_string(),
                tune: None,
                profile: None,
                bitrate_kbps: None,
                max_bitrate_kbps: None,
                buffer_size_kbits: None,
                pass: None,
                level: None,
                gop_size: None,
                bf: None,
                pix_fmt: Some("yuv420p".to_string()),
                b_ref_mode: None,
                rc_lookahead: None,
                spatial_aq: None,
                temporal_aq: None,
            },
            audio: AudioConfig {
                codec: AudioCodecType::Copy,
                bitrate: None,
                sample_rate_hz: None,
                channels: None,
                channel_layout: None,
                loudness_profile: None,
                target_lufs: None,
                loudness_range: None,
                true_peak_db: None,
            },
            filters: FilterConfig {
                scale: None,
                crop: None,
                fps: None,
                vf_chain: None,
                af_chain: None,
                filter_complex: None,
            },
            subtitles: None,
            container: None,
            hardware: None,
            stats: empty_stats(),
            advanced_enabled: Some(false),
            ffmpeg_template: None,
            is_smart_preset: Some(true),
        },
        FFmpegPreset {
            id: "smart-av1-fast".to_string(),
            name: "AV1 Fast (SVT)".to_string(),
            description:
                "libsvtav1 CRF 34 preset 6, 10-bit output keeping source resolution for high-efficiency fast compression."
                    .to_string(),
            description_i18n: None,
            global: None,
            input: None,
            mapping: None,
            video: VideoConfig {
                encoder: EncoderType::LibSvtAv1,
                rate_control: RateControlMode::Crf,
                quality_value: 34,
                preset: "6".to_string(),
                tune: None,
                profile: None,
                bitrate_kbps: None,
                max_bitrate_kbps: None,
                buffer_size_kbits: None,
                pass: None,
                level: None,
                gop_size: Some(240),
                bf: Some(3),
                pix_fmt: Some("yuv420p10le".to_string()),
                b_ref_mode: None,
                rc_lookahead: None,
                spatial_aq: None,
                temporal_aq: None,
            },
            audio: AudioConfig {
                codec: AudioCodecType::Copy,
                bitrate: None,
                sample_rate_hz: None,
                channels: None,
                channel_layout: None,
                loudness_profile: None,
                target_lufs: None,
                loudness_range: None,
                true_peak_db: None,
            },
            filters: FilterConfig {
                scale: None,
                crop: None,
                fps: None,
                vf_chain: None,
                af_chain: None,
                filter_complex: None,
            },
            subtitles: None,
            container: None,
            hardware: None,
            stats: empty_stats(),
            advanced_enabled: Some(false),
            ffmpeg_template: None,
            is_smart_preset: Some(true),
        },
        FFmpegPreset {
            id: "smart-av1-archive".to_string(),
            name: "AV1 Archival (SVT)".to_string(),
            description:
                "libsvtav1 CRF 24 preset 6, 10-bit output tuned for visually lossless archival."
                    .to_string(),
            description_i18n: None,
            global: None,
            input: None,
            mapping: None,
            video: VideoConfig {
                encoder: EncoderType::LibSvtAv1,
                rate_control: RateControlMode::Crf,
                quality_value: 24,
                preset: "6".to_string(),
                tune: None,
                profile: None,
                bitrate_kbps: None,
                max_bitrate_kbps: None,
                buffer_size_kbits: None,
                pass: None,
                level: None,
                gop_size: Some(240),
                bf: Some(3),
                pix_fmt: Some("yuv420p10le".to_string()),
                b_ref_mode: None,
                rc_lookahead: None,
                spatial_aq: None,
                temporal_aq: None,
            },
            audio: AudioConfig {
                codec: AudioCodecType::Copy,
                bitrate: None,
                sample_rate_hz: None,
                channels: None,
                channel_layout: None,
                loudness_profile: None,
                target_lufs: None,
                loudness_range: None,
                true_peak_db: None,
            },
            filters: FilterConfig {
                scale: None,
                crop: None,
                fps: None,
                vf_chain: None,
                af_chain: None,
                filter_complex: None,
            },
            subtitles: None,
            container: None,
            hardware: None,
            stats: empty_stats(),
            advanced_enabled: Some(false),
            ffmpeg_template: None,
            is_smart_preset: Some(true),
        },
    ]
}
