import { stripQuotes } from "../utils";

const KNOWN_OPTION_SET = new Set([
  "-progress",
  "-nostdin",
  "-stats_period",
  "-y",
  "-n",
  "-loglevel",
  "-hide_banner",
  "-report",
  "-ss",
  "-accurate_seek",
  "-stream_loop",
  "-itsoffset",
  "-i",
  "-t",
  "-to",
  "-map",
  "-map_metadata",
  "-map_chapters",
  "-disposition",
  "-metadata",
  "-c:v",
  "-rc",
  "-qp",
  "-crf",
  "-cq",
  "-b:v",
  "-maxrate",
  "-bufsize",
  "-passlogfile",
  "-pass",
  "-preset",
  "-tune",
  "-profile:v",
  "-level",
  "-g",
  "-bf",
  "-pix_fmt",
  "-b_ref_mode",
  "-rc-lookahead",
  "-spatial-aq",
  "-temporal-aq",
  "-c:a",
  "-b:a",
  "-ar",
  "-ac",
  "-channel_layout",
  "-vf",
  "-af",
  "-filter:v",
  "-filter:a",
  "-filter_complex",
  "-sn",
  "-f",
  "-movflags",
  "-hwaccel",
  "-hwaccel_device",
  "-hwaccel_output_format",
  "-bsf",
]);

export const isKnownOption = (token: string): boolean => {
  const raw = stripQuotes(token);
  if (!raw.startsWith("-")) return false;
  if (raw.startsWith("-disposition:")) return true;
  if (raw.startsWith("-passlogfile:")) return true;
  return KNOWN_OPTION_SET.has(raw);
};
