use std::path::{Path, PathBuf};

use specta::Types;
use specta_typescript::Typescript;

use crate::commands::job_compare::JobCompareSources;
use crate::ffui_core::{
    JobSource, JobStatus, JobType, QueueStartupHint, QueueState, QueueStateLiteDelta,
    QueueStateUiLite, TranscodeJob,
};

const GENERATED_HEADER: &str = "\
// This file is generated by src-tauri/src/ipc_contracts.rs.
// Do not edit by hand. Run `pnpm run check:queue-contracts:update` to refresh.

";

const WIRE_ALIASES: &str = "\
export type WireJobStatus = JobStatus;
export type WireJobType = JobType;
export type WireJobSource = JobSource;
export type WireQueueState = QueueState_Serialize;
export type WireQueueStateLite = QueueStateUiLite_Serialize;
export type WireTranscodeJobLite = TranscodeJobUiLite_Serialize;
export type WireQueueStateLiteDelta = QueueStateLiteDelta_Serialize;
export type WireTranscodeJobLiteDeltaPatch = TranscodeJobLiteDeltaPatch_Serialize;
export type WireTranscodeJob = TranscodeJob_Serialize;
export type WireJobCompareSources = JobCompareSources_Serialize;
export type WireQueueStartupHint = QueueStartupHint;
export type WireQueueStartupHintKind = QueueStartupHintKind;
";

pub fn queue_contracts_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("src")
        .join("lib")
        .join("backend")
        .join("generated")
        .join("queue-contracts.ts")
}

fn queue_contract_types() -> Types {
    Types::default()
        .register::<JobStatus>()
        .register::<JobType>()
        .register::<JobSource>()
        .register::<QueueState>()
        .register::<QueueStateUiLite>()
        .register::<QueueStateLiteDelta>()
        .register::<TranscodeJob>()
        .register::<JobCompareSources>()
        .register::<QueueStartupHint>()
}

pub fn generate_queue_contracts_string() -> String {
    let body = Typescript::default()
        .export(&queue_contract_types(), specta_serde::PhasesFormat)
        .expect("export queue contracts");
    let body = body
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    format!("{GENERATED_HEADER}{body}\n{WIRE_ALIASES}")
}

pub fn write_queue_contracts(path: &Path) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create queue contract output directory");
    }
    std::fs::write(path, generate_queue_contracts_string()).expect("write queue contracts");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ffui_core::{
        ProgressPhaseTelemetry, QueueStateUiLite, TranscodeJobUiLite, WaitMetadataUiLite,
    };

    fn representative_lite_job() -> TranscodeJobUiLite {
        TranscodeJobUiLite {
            id: "job-1".to_string(),
            filename: "C:/videos/in.mp4".to_string(),
            job_type: JobType::Video,
            source: JobSource::Manual,
            queue_order: None,
            original_size_mb: 10.0,
            original_codec: None,
            preset_id: "preset-1".to_string(),
            status: JobStatus::Processing,
            wait_request_pending: true,
            progress: 25.0,
            start_time: None,
            end_time: None,
            processing_started_ms: None,
            elapsed_ms: None,
            output_size_mb: None,
            input_path: Some("C:/videos/in.mp4".to_string()),
            created_time_ms: None,
            modified_time_ms: None,
            output_path: None,
            output_policy: None,
            ffmpeg_command: None,
            first_run_command: None,
            first_run_started_at_ms: None,
            skip_reason: None,
            media_info: None,
            estimated_seconds: None,
            preview_path: None,
            preview_revision: 0,
            log_tail: None,
            failure_reason: None,
            warnings: Vec::new(),
            batch_id: None,
            batch_compress_saving_condition: None,
            wait_metadata: Some(WaitMetadataUiLite {
                last_progress_percent: Some(25.0),
                processed_wall_millis: Some(1234),
                processed_seconds: Some(5.0),
                target_seconds: Some(10.0),
                progress_epoch: Some(1),
                last_progress_out_time_seconds: Some(5.0),
                last_progress_speed: Some(1.5),
                last_progress_updated_at_ms: Some(1712345678901),
                last_progress_frame: Some(120),
                tmp_output_path: Some("C:/tmp/seg0.mkv".to_string()),
            }),
            phase_telemetry: ProgressPhaseTelemetry::default(),
        }
    }

    #[test]
    fn queue_state_lite_serde_serializes_queue_order_null() {
        let snapshot = QueueStateUiLite {
            snapshot_revision: 7,
            latest_delta_revision: 0,
            jobs: vec![representative_lite_job()],
        };

        let value = serde_json::to_value(snapshot).expect("serialize queue state lite");

        assert_eq!(value["jobs"][0]["queueOrder"], serde_json::Value::Null);
        assert_eq!(value["jobs"][0]["waitRequestPending"], true);
        assert!(value["jobs"][0]["waitMetadata"].get("segments").is_none());
    }

    #[test]
    fn generated_queue_ipc_contracts_match_committed() {
        let expected = generate_queue_contracts_string();
        let path = queue_contracts_path();

        if std::env::var_os("FFUI_UPDATE_QUEUE_CONTRACTS").is_some() {
            write_queue_contracts(&path);
            return;
        }

        let actual = std::fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!(
                "failed to read generated queue contracts at {}: {err}",
                path.display()
            )
        });

        assert_eq!(
            actual, expected,
            "generated queue IPC contracts are stale; run `pnpm run check:queue-contracts:update`"
        );
    }
}
